export const buzzwords = [
  "*Child noises in the background*",
  "Good morning everyone",
  "Can you see my screen?",
  "You're on mute",
  "Let's take this offline",
  "I'm having VPN issues",
  "Your audio is cutting out",
  "Can you hear me?",
  "I cannot see you..",
  "How long is it going to take?",
  "We're already a few minutes over time..",
  "*Awkward silence*",
  "Hey... nice background!",
  "I'll give you all some time back",
  "Can I share my screen?",
  "I have to drop",
  "I have to jump in another call",
  "Let's set up a working session",
  "Was that your cat?",
  "It looks like nobody's here yet..",
  "Are you in the office?",
  "Let me share my screen",
  `Happy ${new Date().toLocaleDateString("en-US", { weekday: "long" })}!`,
  "I'll be right back",
  "*Coffee break*",
  "Sorry.. my audio cut out",
  "I'll have to get back to you",
  "I was on mute",
  "I was having connection issues",
];
